<a href="https://colab.research.google.com/github/weeraphon-hub/data_viz_2022/blob/main/Data_Stucture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Stucture (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายตัวไว้อย่างเป็นระบบระเบียบ

## ```list()```
- เก็บอะไรไว้ฃก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [320]:
list_a = [1,2,3,4,5,6] # [ ] square blackets

In [321]:
list_a

[1, 2, 3, 4, 5, 6]

In [322]:
list_b = ['ab',2,3.14,list_a] # สามารถเก็บข้อมูลหลายๆแบบไว้ก็ได้

In [323]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [324]:
list_a[3]

4

In [325]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [326]:
list_b[3][4]

5

In [328]:
list_a[6] # ถ้าใส่ตัวแลขใน blackets มากกว่าตัวแปรที่เก็บใน list จะไม่สามารถ รันได้

IndexError: ignored

In [329]:
list_a[-1] # indexing -1 คือดึงตัวสุดท้ายของ list

6

### การสร้าง ```list```

In [330]:
list_x1 = [] # แบบที่ 1
list_x2 = list() # แบบที่ 2

In [331]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```

In [332]:
list_x1.append(2)

In [333]:
list_x1

[2]

In [334]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [335]:
list_x1[0]

2

In [336]:
list_x1[-1]

4

In [337]:
list_x2

[]

In [338]:
list_x2.append('ha')

In [339]:
list_x2

['ha']

In [340]:
list_x1.append('ha')

In [341]:
list_x1

[2, 4, 'ha']

In [342]:
list_x1.pop() # เป็นการลบตัวท้ายสุดใน list ออก

'ha'

In [343]:
list_x1

[2, 4]

In [344]:
list_x1.pop()
print(list_x1)

[2]


### ```len()``` ตรวจสอบจำนวนสมาชิกของ list

In [345]:
print(list_b)

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]


In [346]:
print(len(list_b))

4


In [347]:
len(list_a)

6

### Siring is a list characters

In [348]:
st_stat = 'Department of Statistics, Faculty of Science'

In [349]:
st_stat[10] 

' '

In [350]:
len(st_stat)

44

### List Slicing `:`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย:step (โปร่ง)]`

In [351]:
list_a

[1, 2, 3, 4, 5, 6]

In [352]:
list_a[2]

3

#### ```:``` colon

In [353]:
list_a[-3:] # : colon # เอา 3 ตัวท้าย

[4, 5, 6]

In [354]:
list_a[2:] # : colon # เอาตั้งแต่ตัวที่ 2 ถึงตัวสุดท้าย

[3, 4, 5, 6]

In [355]:
list_a[:4] # : colon # เอาตั้งแต่ตัวแรก ถึง ตัวในตำแหน่งที่ 4

[1, 2, 3, 4]

In [356]:
list_a[1:4] # เอาตั้งแต่ตำแหน่งที่ 1 ถึง ตำแหน่งที่ 3 ไม่เอาตำแหน่งที่ 4

[2, 3, 4]

In [357]:
list_a[:]

[1, 2, 3, 4, 5, 6]

#### step

In [358]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [359]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [360]:
list_c[:10:2] # Step :2 คือจะเริ่มจากตำแหน่งแรกแล้วข้ามตัวถัดไป แล้วก็สลับไปเรื่อยๆ 

[1, 3, 5, 7, 9]

In [361]:
list_c[:10:3] # Step :3 คือจะเริ่มจากตำแหน่งแรกแล้วข้าม 2 ตัวถัดไป แล้วก็สลับไปเรื่อยๆ

[1, 4, 7, 10]

In [362]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### ```range()```

In [363]:
range(21)

range(0, 21)

In [364]:
a = list(range(21))

In [365]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [366]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวนเวลาเป็นวินาทีของเวลาต่อไปนี้ต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาใช้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [367]:
#ex 01:02:03

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [368]:
# 12:30:15
x = 12*60*60 + (30*60) + 15
print(f'12:30:15 แปลงเป็นวินาที ได้ {x:,} วินาที')


12:30:15 แปลงเป็นวินาที ได้ 45,015 วินาที


In [369]:
# 13:41:07
x = '13:41:07'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 49267 วินาที


In [370]:
# 09:11:50
x = '09:11:50'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 33110 วินาที


In [371]:
# 21:30:15
x = '21:30:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 77415 วินาที


In [372]:
# 03:10:15
x = '03:10:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 11415 วินาที


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่สำคัญ

### สร้าง Dictionary

### การชี้สมาชิกใน Dictionary

In [373]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets

In [374]:
dict_a[1]

'Happy'

In [375]:
dict_a['N']

'New'

In [376]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [377]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพื่มสมาชิกลงไปใน Dictionary

In [378]:
dict_a[7] = 3.14

In [379]:
dict_a[5] = 'love' # ลองทำเล่นๆเพราะสงสัย ปัง ปัง ปัง

In [380]:
dict_a # ถ้ากำหนด key ซ้ำจะเป็นการอัพเดตข้อมูลเดิม

{1: 'Happy', '2022': 'Year', 5: 'love', 7: 3.14, 'N': 'New'}

## Nampy Array

- เก็บได้เฉพาะตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็นเมทริกซ์)

### 1D array

In [381]:
import numpy

In [382]:
arr = numpy.array([1,2,3,4,5])

In [383]:
arr

array([1, 2, 3, 4, 5])

In [384]:
arr[0] # ใช้ประโยชน์ได้มากกว่า list

1

In [385]:
5*arr # 5 คูณเข้า array จะหมายถึง คูณทุกตัวในนั้น เหมือนเมทริกซ์

array([ 5, 10, 15, 20, 25])

In [386]:
list_ex =[1,2,3,4,5]

In [387]:
5*list_ex # 5 * list หมายถึงเรียก list 5 รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [388]:
arr2 = numpy.array([10,20,30,40,50])

In [389]:
arr

array([1, 2, 3, 4, 5])

In [390]:
arr + arr2

array([11, 22, 33, 44, 55])

In [391]:
arr * arr2

array([ 10,  40,  90, 160, 250])

In [392]:
arr / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [393]:
arr - arr2

array([ -9, -18, -27, -36, -45])

In [394]:
arr.shape

(5,)

## 2D array

In [395]:
import numpy as np

In [396]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [397]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [398]:
arr2d.shape

(2, 3)

### np.zeros()

In [399]:
arr2350 = np.zeros((3,5))

In [400]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [401]:
arr2350[1,2] = 9

In [402]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [403]:
arr2350[1,2]

9.0

In [404]:
print(list_ex)
list_ex[-1] = 'Song gang'
print(list_ex)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Song gang']


### np.ones()

In [405]:
arr2451 = np.ones((4,5)) # มี 1 เนื่องจากเราสามารถ * ตัวเลขใดเข้าก็ได้ ทำให้เราสามารถ สร้างเมทริกซ์ที่ต้องการได้

In [406]:
arr2451

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [407]:
arr245200 = 200*np.ones((4,5))
arr245200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix Operations

#### การ + - เมทริกซ์ $M \pm N $ เป็นการบวกลบในตำแหน่งเดียวกัน

In [408]:
arr245200 + arr2350 # ขนาดต้องเท่ากันถึงจะบวกกันได้

ValueError: ignored

In [ ]:
arr245200 + arr2451

#### การคูณ matrix

- $aM$ คูณตัวเลขเข้าไปในทุกตำแหน่งของเมทริกซ์
- $M \times N$ (แถว*หลัก)

### $aM$

In [ ]:
15 * arr

$M \times N$ (dot product)

- (m,n) $\times$ (n,W) = (m,w)

In [ ]:
mata = np.array ([[2,3,5],[4,5,7]])
matb = np.array ([[1,2,5],[2,4,-7]])
matc = np.array ([[2,3],[4,6],[7,9]])

In [ ]:
mata

In [ ]:
matb

In [ ]:
matc

ac, bc

In [ ]:
np.dot(mata,matc)

In [409]:
mata * matb # ตำแหน่งของเมทริกซ์ * กันในแต่ละตำแหน่ง

array([[  2,   6,  25],
       [  8,  20, -49]])

### Matrix Slicing

In [410]:
mat[:2,:2]

NameError: ignored

HW3

1. สร้าง array ที่มีรูปต้น Chrismas
2. slice เลข 1 ออกมากเป็น array HW3 ด้วยการ slice แค้ครั้งเดียว

In [473]:
CM = np.ones((20,15))
CM

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [474]:
CM[19,6:9] = 8
CM[18,6:9] = 8
CM[17,6:9] = 8
CM[16,1:14] =8
CM[15,1:14] = 8
CM[14,2:13] = 8
CM[13,3:12] = 8
CM[12,4:11] = 8
CM[11,2:13] = 8
CM[10,3:12] = 8
CM[9,4:11] = 8
CM[8,5:10] = 8
CM[6,3:12] = 8
CM[7,3:12] = 8
CM[5,4:11] = 8
CM[4,5:10] = 8
CM[3,6:9] = 8
CM[2,7] = 8
CM[2,7] = 8
CM[1,6:9] = 5
CM[0,6] = 5
CM[0,8] = 5
CM

array([[1., 1., 1., 1., 1., 1., 5., 1., 5., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 5., 5., 5., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 8., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8.