<a href="https://colab.research.google.com/github/weeraphon-hub/data_viz_2022/blob/main/Data_Stucture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Stucture (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายตัวไว้อย่างเป็นระบบระเบียบ

## ```list()```
- เก็บอะไรไว้ฃก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [8]:
list_a = [1,2,3,4,5,6] # [ ] square blackets

In [9]:
list_a

[1, 2, 3, 4, 5, 6]

In [10]:
list_b = ['ab',2,3.14,list_a] # สามารถเก็บข้อมูลหลายๆแบบไว้ก็ได้

In [11]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [12]:
list_a[3]

4

In [13]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [24]:
list_b[3][4]

5

In [25]:
list_a[6] # ถ้าใส่ตัวแลขใน blackets มากกว่าตัวแปรที่เก็บใน list จะไม่สามารถ รันได้

IndexError: ignored

In [26]:
list_a[-1] # indexing -1 คือดึงตัวสุดท้ายของ list

6

### การสร้าง ```list```

In [27]:
list_x1 = [] # แบบที่ 1
list_x2 = list() # แบบที่ 2

In [28]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```

In [29]:
list_x1.append(2)

In [30]:
list_x1

[2]

In [31]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [32]:
list_x1[0]

2

In [33]:
list_x1[-1]

4

In [34]:
list_x2

[]

In [35]:
list_x2.append('ha')

In [36]:
list_x2

['ha']

In [37]:
list_x1.append('ha')

In [38]:
list_x1

[2, 4, 'ha']

In [39]:
list_x1.pop() # เป็นการลบตัวท้ายสุดใน list ออก

'ha'

In [40]:
list_x1

[2, 4]

In [41]:
list_x1.pop()
print(list_x1)

[2]


### ```len()``` ตรวจสอบจำนวนสมาชิกของ list

In [42]:
print(list_b)

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]


In [43]:
print(len(list_b))

4


In [44]:
len(list_a)

6

### Siring is a list characters

In [45]:
st_stat = 'Department of Statistics, Faculty of Science'

In [46]:
st_stat[10] 

' '

In [47]:
len(st_stat)

44

### List Slicing `:`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย:step (โปร่ง)]`

In [48]:
list_a

[1, 2, 3, 4, 5, 6]

In [49]:
list_a[2]

3

#### ```:``` colon

In [50]:
list_a[-3:] # : colon # เอา 3 ตัวท้าย

[4, 5, 6]

In [51]:
list_a[2:] # : colon # เอาตั้งแต่ตัวที่ 2 ถึงตัวสุดท้าย

[3, 4, 5, 6]

In [52]:
list_a[:4] # : colon # เอาตั้งแต่ตัวแรก ถึง ตัวในตำแหน่งที่ 4

[1, 2, 3, 4]

In [53]:
list_a[1:4] # เอาตั้งแต่ตำแหน่งที่ 1 ถึง ตำแหน่งที่ 3 ไม่เอาตำแหน่งที่ 4

[2, 3, 4]

In [54]:
list_a[:]

[1, 2, 3, 4, 5, 6]

#### step

In [55]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [56]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [57]:
list_c[:10:2] # Step :2 คือจะเริ่มจากตำแหน่งแรกแล้วข้ามตัวถัดไป แล้วก็สลับไปเรื่อยๆ 

[1, 3, 5, 7, 9]

In [58]:
list_c[:10:3] # Step :3 คือจะเริ่มจากตำแหน่งแรกแล้วข้าม 2 ตัวถัดไป แล้วก็สลับไปเรื่อยๆ

[1, 4, 7, 10]

In [59]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### ```range()```

In [60]:
range(21)

range(0, 21)

In [61]:
a = list(range(21))

In [62]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [63]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวนเวลาเป็นวินาทีของเวลาต่อไปนี้ต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาใช้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [64]:
#ex 01:02:03

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [65]:
# 12:30:15
x = 12*60*60 + (30*60) + 15
print(f'12:30:15 แปลงเป็นวินาที ได้ {x:,} วินาที')


12:30:15 แปลงเป็นวินาที ได้ 45,015 วินาที


In [66]:
# 13:41:07
x = '13:41:07'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 49267 วินาที


In [67]:
# 09:11:50
x = '09:11:50'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 33110 วินาที


In [68]:
# 21:30:15
x = '21:30:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 77415 วินาที


In [69]:
# 03:10:15
x = '03:10:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 11415 วินาที


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่สำคัญ

### สร้าง Dictionary

### การชี้สมาชิกใน Dictionary

In [70]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets

In [71]:
dict_a[1]

'Happy'

In [72]:
dict_a['N']

'New'

In [73]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [74]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพื่มสมาชิกลงไปใน Dictionary

In [75]:
dict_a[7] = 3.14

In [76]:
dict_a[5] = 'love' # ลองทำเล่นๆเพราะสงสัย ปัง ปัง ปัง

In [77]:
dict_a # ถ้ากำหนด key ซ้ำจะเป็นการอัพเดตข้อมูลเดิม

{1: 'Happy', '2022': 'Year', 5: 'love', 7: 3.14, 'N': 'New'}

## Nampy Array

- เก็บได้เฉพาะตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็นเมทริกซ์)

### 1D array

In [78]:
import numpy

In [79]:
arr = numpy.array([1,2,3,4,5])

In [80]:
arr

array([1, 2, 3, 4, 5])

In [81]:
arr[0] # ใช้ประโยชน์ได้มากกว่า list

1

In [82]:
5*arr # 5 คูณเข้า array จะหมายถึง คูณทุกตัวในนั้น เหมือนเมทริกซ์

array([ 5, 10, 15, 20, 25])

In [83]:
list_ex =[1,2,3,4,5]

In [84]:
5*list_ex # 5 * list หมายถึงเรียก list 5 รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [85]:
arr2 = numpy.array([10,20,30,40,50])

In [86]:
arr

array([1, 2, 3, 4, 5])

In [87]:
arr + arr2

array([11, 22, 33, 44, 55])

In [88]:
arr * arr2

array([ 10,  40,  90, 160, 250])

In [89]:
arr / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [90]:
arr - arr2

array([ -9, -18, -27, -36, -45])

In [91]:
arr.shape

(5,)

## 2D array

In [92]:
import numpy as np

In [93]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
arr2d.shape

(2, 3)

### np.zeros()

In [96]:
arr2350 = np.zeros((3,5))

In [97]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [98]:
arr2350[1,2] = 9

In [99]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
arr2350[1,2]

9.0

In [101]:
print(list_ex)
list_ex[-1] = 'Song gang'
print(list_ex)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Song gang']


### np.ones()

In [102]:
arr2451 = np.ones((4,5)) # มี 1 เนื่องจากเราสามารถ * ตัวเลขใดเข้าก็ได้ ทำให้เราสามารถ สร้างเมทริกซ์ที่ต้องการได้

In [103]:
arr2451

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
arr245200 = 200*np.ones((4,5))
arr245200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix Operations

#### การ + - เมทริกซ์ $M \pm N $ เป็นการบวกลบในตำแหน่งเดียวกัน

In [105]:
arr245200 + arr2350 # ขนาดต้องเท่ากันถึงจะบวกกันได้

ValueError: ignored

In [106]:
arr245200 + arr2451

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix

- $aM$ คูณตัวเลขเข้าไปในทุกตำแหน่งของเมทริกซ์
- $M \times N$ (แถว*หลัก)

### $aM$

In [107]:
15 * arr

array([15, 30, 45, 60, 75])

$M \times N$ (dot product)

- (m,n) $\times$ (n,W) = (m,w)

In [108]:
mata = np.array ([[2,3,5],[4,5,7]])
matb = np.array ([[1,2,5],[2,4,-7]])
matc = np.array ([[2,3],[4,6],[7,9]])

In [109]:
mata

array([[2, 3, 5],
       [4, 5, 7]])

In [110]:
matb

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [111]:
matc

array([[2, 3],
       [4, 6],
       [7, 9]])

ac, bc

In [112]:
np.dot(mata,matc)

array([[ 51,  69],
       [ 77, 105]])

In [113]:
mata * matb # ตำแหน่งของเมทริกซ์ * กันในแต่ละตำแหน่ง

array([[  2,   6,  25],
       [  8,  20, -49]])

### Matrix Slicing

In [114]:
mat[:2,:2]

NameError: ignored

HW3

1. สร้าง array ที่มีรูปต้น Chrismas
2. slice เลข 1 ออกมากเป็น array HW3 ด้วยการ slice แค้ครั้งเดียว

In [143]:
CM2 = np.ones((30,13))
CM2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 

In [153]:
CM2[26:,1:7]=55
CM2[23:,7:12]=77
CM2[23:26,5:7]=99
CM2[21:23,5:8]=99
CM2[20,0:]=99
CM2[19,1:12]=99
CM2[18,2:11]=99
CM2[17,3:10]=99
CM2[16,4:9]=99
CM2[15,1:12]=99
CM2[14,2:11]=99
CM2[13,3:10]=99
CM2[12,4:9]=99
CM2[11,5:8]=99
CM2[10,2:11]=99
CM2[9,3:10]=99
CM2[8,4:9]=99
CM2[7,5:8]=99
CM2[4:7,6]=99
CM2[5,4]=33
CM2[4,5]=33
CM2[3,6]=33
CM2[2,7]=33
CM2[1,8]=33
CM2[1,4]=33
CM2[2,5]=33
CM2[4,7]=33
CM2[5,8]=33
CM2

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 33.,  1.,  1.,  1., 33.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 33.,  1., 33.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 33.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 33., 99., 33.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 33.,  1., 99.,  1., 33.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 99., 99., 99.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 99., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 99., 99., 99., 99.,  1.,  1.,  1.],
       [ 1.,  1., 99., 99., 99., 99., 99., 99., 99., 99., 99.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 99., 99., 99.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99., 99., 99., 99., 99.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 99., 99., 99., 

In [154]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [155]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [156]:
# slice
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])