<a href="https://colab.research.google.com/github/weeraphon-hub/data_viz_2022/blob/main/Data_Stucture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Stucture (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายตัวไว้อย่างเป็นระบบระเบียบ

## ```list()```
- เก็บอะไรไว้ฃก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [1]:
list_a = [1,2,3,4,5,6] # [ ] square blackets

In [2]:
list_a

[1, 2, 3, 4, 5, 6]

In [3]:
list_b = ['ab',2,3.14,list_a] # สามารถเก็บข้อมูลหลายๆแบบไว้ก็ได้

In [4]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [5]:
list_a[3]

4

In [6]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [7]:
list_b[3][4]

5

In [10]:
list_a[6] # ถ้าใส่ตัวแลขใน blackets มากกว่าตัวแปรที่เก็บใน list จะไม่สามารถ รันได้

IndexError: ignored

In [11]:
list_a[-1] # indexing -1 คือดึงตัวสุดท้ายของ list

6

### การสร้าง ```list```

In [12]:
list_x1 = [] # แบบที่ 1
list_x2 = list() # แบบที่ 2

In [13]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```

In [14]:
list_x1.append(2)

In [15]:
list_x1

[2]

In [16]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [17]:
list_x1[0]

2

In [18]:
list_x1[-1]

4

In [19]:
list_x2

[]

In [20]:
list_x2.append('ha')

In [21]:
list_x2

['ha']

In [22]:
list_x1.append('ha')

In [23]:
list_x1

[2, 4, 'ha']

In [24]:
list_x1.pop() # เป็นการลบตัวท้ายสุดใน list ออก

'ha'

In [25]:
list_x1

[2, 4]

In [26]:
list_x1.pop()
print(list_x1)

[2]


### ```len()``` ตรวจสอบจำนวนสมาชิกของ list

In [27]:
print(list_b)

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]


In [28]:
print(len(list_b))

4


In [29]:
len(list_a)

6

### Siring is a list characters

In [30]:
st_stat = 'Department of Statistics, Faculty of Science'

In [31]:
st_stat[10] 

' '

In [32]:
len(st_stat)

44

### List Slicing `:`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

   `list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย:step (โปร่ง)]`

In [33]:
list_a

[1, 2, 3, 4, 5, 6]

In [34]:
list_a[2]

3

#### ```:``` colon

In [35]:
list_a[-3:] # : colon # เอา 3 ตัวท้าย

[4, 5, 6]

In [36]:
list_a[2:] # : colon # เอาตั้งแต่ตัวที่ 2 ถึงตัวสุดท้าย

[3, 4, 5, 6]

In [37]:
list_a[:4] # : colon # เอาตั้งแต่ตัวแรก ถึง ตัวในตำแหน่งที่ 4

[1, 2, 3, 4]

In [38]:
list_a[1:4] # เอาตั้งแต่ตำแหน่งที่ 1 ถึง ตำแหน่งที่ 3 ไม่เอาตำแหน่งที่ 4

[2, 3, 4]

In [39]:
list_a[:]

[1, 2, 3, 4, 5, 6]

#### step

In [40]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [41]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [42]:
list_c[:10:2] # Step :2 คือจะเริ่มจากตำแหน่งแรกแล้วข้ามตัวถัดไป แล้วก็สลับไปเรื่อยๆ 

[1, 3, 5, 7, 9]

In [43]:
list_c[:10:3] # Step :3 คือจะเริ่มจากตำแหน่งแรกแล้วข้าม 2 ตัวถัดไป แล้วก็สลับไปเรื่อยๆ

[1, 4, 7, 10]

In [44]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### ```range()```

In [45]:
range(21)

range(0, 21)

In [46]:
a = list(range(21))

In [47]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [48]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวนเวลาเป็นวินาทีของเวลาต่อไปนี้ต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาใช้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [49]:
#ex 01:02:03

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [57]:
# 12:30:15
x = 12*60*60 + (30*60) + 15
print(f'12:30:15 แปลงเป็นวินาที ได้ {x:,} วินาที')


12:30:15 แปลงเป็นวินาที ได้ 45,015 วินาที


In [51]:
# 13:41:07
x = '13:41:07'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 49267 วินาที


In [52]:
# 09:11:50
x = '09:11:50'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 33110 วินาที


In [53]:
# 21:30:15
x = '21:30:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 77415 วินาที


In [54]:
# 03:10:15
x = '03:10:15'
xx = x.split(':')
xxx = int(xx[0])*60*60 + int(xx[1])*60 + int(xx[2])
print(f'เวลา 01:02:03 แปลงเป็นวินาทีได้ {xxx} วินาที')

เวลา 01:02:03 แปลงเป็นวินาทีได้ 11415 วินาที


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่สำคัญ

### สร้าง Dictionary

### การชี้สมาชิกใน Dictionary

In [59]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets

In [60]:
dict_a[1]

'Happy'

In [62]:
dict_a['N']

'New'

In [67]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [66]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพื่มสมาชิกลงไปใน Dictionary

In [72]:
dict_a[7] = 3.14

In [79]:
dict_a[5] = 'love' # ลองทำเล่นๆเพราะสงสัย ปัง ปัง ปัง

In [80]:
dict_a # ถ้ากำหนด key ซ้ำจะเป็นการอัพเดตข้อมูลเดิม

{1: 'Happy', '2022': 'Year', 5: 'love', 7: 3.14, 'N': 'New'}

## Nampy Array

- เก็บได้เฉพาะตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็นเมทริกซ์)

### 1D array

In [82]:
import numpy

In [83]:
arr = numpy.array([1,2,3,4,5])

In [84]:
arr

array([1, 2, 3, 4, 5])

In [85]:
arr[0] # ใช้ประโยชน์ได้มากกว่า list

1

In [86]:
5*arr # 5 คูณเข้า array จะหมายถึง คูณทุกตัวในนั้น เหมือนเมทริกซ์

array([ 5, 10, 15, 20, 25])

In [87]:
list_ex =[1,2,3,4,5]

In [89]:
5*list_ex # 5 * list หมายถึงเรียก list 5 รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [90]:
arr2 = numpy.array([10,20,30,40,50])

In [91]:
arr

array([1, 2, 3, 4, 5])

In [92]:
arr + arr2

array([11, 22, 33, 44, 55])

In [93]:
arr * arr2

array([ 10,  40,  90, 160, 250])

In [94]:
arr / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [95]:
arr - arr2

array([ -9, -18, -27, -36, -45])

In [101]:
arr.shape

(5,)

## 2D array

In [96]:
import numpy as np

In [98]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [99]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr2d.shape

(2, 3)

### np.zeros()

In [106]:
arr2350 = np.zeros((3,5))

In [107]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [110]:
arr2350[1,2] = 9

In [111]:
arr2350

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [112]:
arr2350[1,2]

9.0

In [114]:
print(list_ex)
list_ex[-1] = 'Song gang'
print(list_ex)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Song gang']


### np.ones()

In [117]:
arr2451 = np.ones((4,5)) # มี 1 เนื่องจากเราสามารถ * ตัวเลขใดเข้าก็ได้ ทำให้เราสามารถ สร้างเมทริกซ์ที่ต้องการได้

In [119]:
arr2451

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [122]:
arr245200 = 200*np.ones((4,5))
arr245200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix Operations

#### การ + - เมทริกซ์ $M \pm N $ เป็นการบวกลบในตำแหน่งเดียวกัน

In [124]:
arr245200 + arr2350 #

ValueError: ignored

In [126]:
arr245200 + arr2451

array([[400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.]])

#### การคูณ matrix

- $aM$ คูณตัวเลขเข้าไปในทุกตำแหน่งของเมทริกซ์
- $M \times N$ (แถว*หลัก)

### $aM$

In [127]:
15 * arr

array([15, 30, 45, 60, 75])

$M \times N$ (dot product)

- (m,n) $\times$ (n,W) = (m,w)

In [128]:
mata = np.array ([[2,3,5],[4,5,7]])
matb = np.array ([[1,2,5],[2,4,-7]])
matc = np.array ([[2,3],[4,6],[7,9]])

In [129]:
mata

array([[2, 3, 5],
       [4, 5, 7]])

In [130]:
matb

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [131]:
matc

array([[2, 3],
       [4, 6],
       [7, 9]])

ac, bc

In [134]:
np.dot(mata,matc)

array([[ 51,  69],
       [ 77, 105]])

In [137]:
mata * matb #

array([[  2,   6,  25],
       [  8,  20, -49]])

### Matrix Slicing

In [138]:
mat[:2,:2]

NameError: ignored

HW3

1. สร้าง array ที่มีรูปต้น Chrismas
2. slice เลข 1 ออกมากเป็น array HW3 ด้วยการ slice แค้ครั้งเดียว

In [146]:
3 = np.zeros((15,15))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

## Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)